### ISSUE TITLE
Error in .xib file

### ISSUE THREAD

**Issue by Angledor** [xamarin/monotouch-samples#1]
Hello,
When I open and build monocatalog-md solution (and all other monodevelop solutions),
50% of the xib file generate this error on build process :
XXXXViewController.xib: Error: Unknown char: . (monocatalog)
I use new version of MonoDevelop v 2.4 (SVN revision 159698).
Do you have an idea ? Could you help me ?
Thanks
Julien

**Comment by rzaitov** [comment]
This is very old issue. Today I cant reproduce it. so I am going to close it
