### ISSUE TITLE
LazyTableImages is not match to LazyTableImages from Apple

### ISSUE THREAD

**Issue by MaximKorobov** [xamarin/monotouch-samples#16]
In Apple example https://developer.apple.com/library/ios/#samplecode/LazyTableImages/Introduction/Intro.html images are loads when UITableView stops scrolling.
In xamarin / monotouch-samples / LazyTableImages any images are loads consequentially after cells are showing.

These examples have different behavior.

**Comment by rzaitov** [comment]
This is ok.
