### ISSUE TITLE
ImageProtocol sample seems broken(Xamarin.iOS v.6.2.7.1)

### ISSUE THREAD

**Issue by volaticus** [xamarin/monotouch-samples#28]
Hi, 
I built the ImageProtocol sample with X.iOS 6.2.7.1 - XCode 4.6.3 - IPhoneSimulator 6.1 and after launch WebView shows just clear white area. No errors while loading test.html are pushed through UIWebView's LoadError event. Seems that ImageProtocol GetCanonicalRequest&StartLoading methods never called. Port of this sample code to obj-c works as expected.

Any help would be appreciated.

**Comment by rzaitov** [comment]
Works with current stable
