### ISSUE TITLE
MediaPlayer sample - Not working??

### ISSUE THREAD

**Issue by efontana** [xamarin/monotouch-samples#3]
Hi, 
I built the MediaPlayer sample with MT 4.0 / XCode 4.0 / ioS 4.3 and when I click "Local" and "Play Movie" nothing happens.

The console spits out the URL for the movie, then says "Content Preload Finished"... No movie, on Simulator or Phone?

Am I doing something wrong?

**Comment by rzaitov** [comment]
It was ever so many years ago.
