### ISSUE TITLE
Error "property list invalid for format 200 (property lists cannot contain null)" when use MPMoviePlayerController 

### ISSUE THREAD

**Issue by kenpi04** [xamarin/monotouch-samples#38]
I run samples using MPMoviePlayerController!
http://developer.xamarin.com/samples/MoviePlayback/
But video not play!
and view log i recive error "property list invalid for format 200 (property lists cannot contain null)"

Please help me! thank!

**Comment by Arpit360** [comment]
I have checked this issue with XI 9.8.1.4 and its works for me without any error.

Environment Info:  https://gist.github.com/Arpit360/c7156184af3cd48675672d0324c615d9
