### ISSUE TITLE
Sound sample doesnt work in iOS 8

### ISSUE THREAD

**Issue by radiofish** [xamarin/monotouch-samples#40]
The sound example which I am using for my app is no longer working with the latest iOS SDK 8.

The PrepareToRecord method returns false and the app errors out.

Any updates coming?

**Comment by rzaitov** [comment]
fixed. You are right the following is wrong
NSBundle.MainBundle.BundlePath + "/../tmp/" + fileName;

I fixed the sample. Also I replaced old xib files with cute storyboard
