### ISSUE TITLE
Signature Mismatch in TransitionsDemo.InteractionControllers.CEHorizontalSwipeInteractionController.HandleGesture

### ISSUE THREAD

**Issue by therealjohn** [xamarin/monotouch-samples#44]
https://github.com/xamarin/monotouch-samples/blob/master/TransitionsDemo/TransitionsDemo/InteractionControllers/CEHorizontalSwipeInteractionController.cs#L27

Should read `HandleGesture:`

So should https://github.com/xamarin/monotouch-samples/blob/master/TransitionsDemo/TransitionsDemo/InteractionControllers/CEVerticalSwipeInteractionController.cs#L33

**Comment by rzaitov** [comment]
fixed https://github.com/xamarin/monotouch-samples/commit/0bddd07429ad16761e83950cbc081c8fe6593a08
