### ISSUE TITLE
Audio Samples Not Working

### ISSUE THREAD

**Issue by mgamache** [xamarin/monotouch-samples#45]
I am looking to work with audio and many of the iOS samples are working with xcode 6. 

avTouch - XIB has an error won't compile
converter demo - never finishes rendering (I didn't bother debugging) 
APTapQueue - I can't get any sound to play (although it looks like it's processing data) 

maybe it's just me, but these are kind of old and might need updating.

**Comment by rzaitov** [comment]
I checked these samples with current stable and they work fine.
avTouch – compiles and run
AQTapDemo – was fixed a month ago
AudioConverterFileConverter – was fixed a few months ago

Please check it again. If you have any troubles just reopen this issue
