### ISSUE TITLE
In the iOS project PhoneWord (MultiScreen)

### ISSUE THREAD

**Issue by ssramvinay** [xamarin/monotouch-samples#57]
There is a line as given below in the file CallHistoryController.cs.May i know what is CallHistoryCell and should i need to create a Xib file  or not required? Please reply.

static NSString callHistoryCellId = new NSString ("CallHistoryCell");

**Comment by conceptdev** [comment]
questions like this are better posted to the [forums](http://forums.xamarin.com/categories/ios) - raise issues for bugs and errors here.

the answer is: `"CallHistoryCell"` is just a string identifier that is added to each cell instance that is created, so they can be retrieved and re-used.

read the [working with tables and cells documentation](http://developer.xamarin.com/guides/ios/user_interface/tables/) for more info, specifically the [notes on cell re-use](http://developer.xamarin.com/guides/ios/user_interface/tables/part_2_-_populating_a_table_with_data/#Note_on_Cell_Reuse)
