### ISSUE TITLE
Touches_GestureRecognizers with unknown item type

### ISSUE THREAD

**Issue by Emasoft** [xamarin/monotouch-samples#6]
The Touches_GestureRecognizers project doesn't load in MonoDevelop 2.6. It gives me the following error:

Could not load project '/Users/Emanuele/Projects/xamarin-monotouch-samples/Touches/Touches_GestureRecognizers/Touches_GestureRecognizers/Touches_GestureRecognizers.csproj' with unknown item type '{6BC8ED88-2882-458C-8E55-DFD12B67127B};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}'

**Comment by rzaitov** [comment]
Worked with current stable. Also I resolved warnings
