### ISSUE TITLE
Is it possible to create csharp bindings from swig for use in both android and ios projects.

### ISSUE THREAD

**Issue by redbrain** [xamarin/monotouch-samples#60]

**Comment by conceptdev** [comment]
Hi @redbrain! This issues list is generally used to address specific issues with the samples in this repo.

You can raise suggestions on our [UserVoice](https://xamarin.uservoice.com) and ask on [our forums](http://forums.xamarin.com/) (there has already been a [little discussion on swig](http://forums.xamarin.com/search?Search=swig)).

Thanks
