### ISSUE TITLE
AstroLayout

### ISSUE THREAD

**Issue by mac10688** [xamarin/monotouch-samples#61]
Upon trying to build AstroLayout I get about 84 build errors. A lot of missing assembly references.

Class
UILayoutGuide

Methods:
SetIdentifier which should be attached to NSLayoutConstraint.

Properties:
HeightAnchor on UIImageView
CenterXAnchor on UIImageView
WidthAnchor on UIImageView

What am I missing?

**Comment by mac10688** [comment]
I guess it's because I don't have xcode 7?

**Comment by pjbeaman** [comment]
Yes, Xcode 7 is a requirement (see the README). See more about how best to use iOS 9 with Xamarin on http://developer.xamarin.com/guides/ios/platform_features/introduction_to_ios9/
