### ISSUE TITLE
FourInARow incorrectly returns null from Board.Copy(NSZone), which causes GKMinMaxStrategist to fail

### ISSUE THREAD

**Issue by lobrien** [xamarin/monotouch-samples#62]
In FourInARow, Board.Copy(NSZone) cannot return null.

If it returns null, the GKMinMaxStrategist does not properly evaluate potential moves. 

To reproduce: add a static counter to Board.ScoreForPlayer and you will see that it is only called a single time. 

If you rewrite Board.Copy(NSZone) to return a clone, it will be called dozens of times, similarly as to how it is called in Apple's version. 

Partial solution: Board.Copy(NSZone) should return a clone of *this*, similar to Apple's :+1: 

- (__nonnull id)copyWithZone:(nullable NSZone *)zone {
    AAPLBoard *copy = [[[self class] allocWithZone:zone] init];
    [copy setGameModel:self];
    return copy;
}

Problem: When I did this, it appears that several AI moves are executed simultaneously.

**Comment by olegoid** [comment]
Thanks for filling this issue @lobrien! Bug fixed in this commit d092559389b5eaf3f9a9d4a62b837d0d62dd40bc
