### ISSUE TITLE
Error Loading Any tvOS Samples

### ISSUE THREAD

**Issue by jamesbar2** [xamarin/monotouch-samples#66]
I'm running the latest alpha of Xamarin Studio and receiving "Could not load project 'Hello-tvOS/Hello-tvOS.csproj' with unknown item type '{06FA79CB-D6CD-4721-BB4B-1BD202089C55}'" error message.

I'm running Xamarin Studio 5.10 (build 860), from the alpha channel.  I was hoping Alpha would pull in what I needed.  Anybody else having this issue?

**Comment by olegoid** [comment]
Hi @jamesbar2, at this point we don't have support for tvOS in public channels(alpha, beta, stable). However you can download  tvOS preview builds from this [page](https://developer.xamarin.com/guides/ios/tvos/#Installing_tvOS_Support).

Hope it will help,
Thanks
