### ISSUE TITLE
Homekit Intro files the wrong type

### ISSUE THREAD

**Issue by bridgewaterrobbie** [xamarin/monotouch-samples#67]
Most of your home kit intro sample files seem to be .cs files rather than the correct type

**Comment by olegoid** [comment]
Hi @bridgewaterrobbie! I don't think that I understood the problem. Could you describe what is "correct type" of files in your opinion?

**Comment by olegoid** [comment]
Closing this issue for now, since no additional information was provided. @bridgewaterrobbie please let me know if we can help you somehow with HomeKit and Xamarin.
