### ISSUE TITLE
Many of the samples in iOS8 and iOS9 retain the Apple copyright stamp.

### ISSUE THREAD

**Issue by MichaelNorman** [xamarin/monotouch-samples#68]
Was digging through old mail when I saw that this issue had been brought up ages ago, but clearly remembered seeing it just that day. I've dug around since then and, sure enough, Apply copybugs are everywhere in iOS[8|9] directories. Might be elsewhere, too. These should probably be removed, and whatever translation tool is being used should be updated to not put the copybugs in.

Cheers!

**Comment by rzaitov** [comment]
Hello @MichaelNorman!
Are you talking about **Copyright (C) 2014 Apple Inc. All rights reserved.**? Like this one under Author section?
https://github.com/xamarin/monotouch-samples/blob/a86e44c38d01a9932209d151b4985e0b80e05b3e/ios8/CloudKitAtlas/README.md#author

If so, this is expected. Technically author of this sample is Apple we just translate Apple's sample to another language.

This *copybug* from this [template](https://github.com/xamarin/private-samples/blob/master/README.md)

**Comment by olegoid** [comment]
Fix merged to master: 067ab280f43c5230193d676e9df83de03672b2a4
