### ISSUE TITLE
Can't find a MonoTouch port of the GLImageProcessing sample project

### ISSUE THREAD

**Issue by Emasoft** [xamarin/monotouch-samples#7]
I can't find the GLImageProcessing example project from the Apple documentation:

http://developer.apple.com/library/ios/#samplecode/GLImageProcessing/Introduction/Intro.html

A MonoTouch version of that would be very useful to learn, allowing fast image processing of UIImages using the iPhone and iPad GPU, making filters like blur or  to 24 times faster.

**Comment by olegoid** [comment]
Hi @Emasoft, we have another sample with pretty much the same functionality - [GLKBaseEffectDrawingTexture](https://github.com/xamarin/monotouch-samples/tree/master/OpenGL/GLKBaseEffectDrawingTexture). Also we have [a bunch of other OpenGL samples](https://github.com/xamarin/monotouch-samples/tree/master/OpenGL) in our gallery
